export const BACKGROUND_TOTAL_ROUNDED = "BACKGROUND_TOTAL_ROUNDED"
export const BACKGROUND_PARTIAL_ROUNDED = "BACKGROUND_PARTIAL_ROUNDED"
export const NO_BACKGROUND = "NO_BACKGROUND"

export const MAIN_TEXT_COLOR = "#000"
export const SECONDARY_TEXT_COLOR = "#d6ff41"
export const TERTIARY_TEXT_COLOR = "#fff"